title: Huasheng Huang
subtitle: PhD candidate UvA
description: Website and portfolio of Huasheng Huang, PhD candidate.

author: Huasheng Huang
email: buxushuang@gmail.com
avatar: assets/images/me.jpg

baseurl: ""
url: "https://huashenghuang.github.io"

# Social settings
github_url: https://github.com/huashenghuang

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
